name: ProtocolSupportLegacySupport
main: protocolsupportlegacysupport.ProtocolSupportLegacySupport
api-version: 1.17
depend: [ProtocolSupport, ProtocolLib]
load: STARTUP
version: ${version}

commands:
  protocolsupportlegacysupport:
    description: All ProtocolSupportLegacySupport commands
    aliases:
    - psls
    usage: '/protocolsupportlegacysupport reload'

author: _Shevchik_
