name: ProtocolSupportLegacySupport
main: protocolsupportlegacysupport.ProtocolSupportLegacySupport
version: ${version}
api-version: 1.16
load: STARTUP
depend: [ProtocolSupport, ProtocolLib]

commands:
  protocolsupportlegacysupport:
    description: All ProtocolSupportLegacySupport commands
    aliases:
    - psls
    usage: '/protocolsupportlegacysupport reload'

author: _Shevchik_
